CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'accounting') THEN
        CREATE SCHEMA accounting;
    END IF;
END $EF$;

CREATE TABLE public."Statuses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Statuses" PRIMARY KEY ("Id")
);

CREATE TABLE accounting."Accounts" (
    "Id" text NOT NULL,
    "AccountNumber" text,
    "GSTNumber" text,
    "PANNumber" text,
    "Balance" double precision NOT NULL,
    "Name" text,
    "Description" text,
    "UniqueIdentifier" text,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedDate" timestamp with time zone,
    "CreatedBy" text,
    "ModifiedBy" text,
    "StatusId" integer NOT NULL,
    "LastStatusId" integer,
    "StatusChangedBy" text,
    "StatusChangedDate" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Accounts_Statuses_LastStatusId" FOREIGN KEY ("LastStatusId") REFERENCES public."Statuses" ("Id"),
    CONSTRAINT "FK_Accounts_Statuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES public."Statuses" ("Id") ON DELETE CASCADE
);

CREATE TABLE accounting."TransactionTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Multiplier" integer NOT NULL,
    "Name" text,
    "Description" text,
    "UniqueIdentifier" text,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedDate" timestamp with time zone,
    "CreatedBy" text,
    "ModifiedBy" text,
    "StatusId" integer NOT NULL,
    "LastStatusId" integer,
    "StatusChangedBy" text,
    "StatusChangedDate" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_TransactionTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TransactionTypes_Statuses_LastStatusId" FOREIGN KEY ("LastStatusId") REFERENCES public."Statuses" ("Id"),
    CONSTRAINT "FK_TransactionTypes_Statuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES public."Statuses" ("Id") ON DELETE CASCADE
);

CREATE TABLE accounting."AccountTransactions" (
    "Id" text NOT NULL,
    "AccountId" text,
    "Amount" double precision NOT NULL,
    "TransactionDate" timestamp with time zone NOT NULL,
    "TransactionTypeId" integer NOT NULL,
    "Name" text,
    "Description" text,
    "UniqueIdentifier" text,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedDate" timestamp with time zone,
    "CreatedBy" text,
    "ModifiedBy" text,
    "StatusId" integer NOT NULL,
    "LastStatusId" integer,
    "StatusChangedBy" text,
    "StatusChangedDate" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_AccountTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AccountTransactions_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES accounting."Accounts" ("Id"),
    CONSTRAINT "FK_AccountTransactions_Statuses_LastStatusId" FOREIGN KEY ("LastStatusId") REFERENCES public."Statuses" ("Id"),
    CONSTRAINT "FK_AccountTransactions_Statuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES public."Statuses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AccountTransactions_TransactionTypes_TransactionTypeId" FOREIGN KEY ("TransactionTypeId") REFERENCES accounting."TransactionTypes" ("Id") ON DELETE CASCADE
);

INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (1, TRUE, 'Draft');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (2, TRUE, 'WaitingForApproval');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (3, TRUE, 'Approved');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (4, TRUE, 'Published');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (5, TRUE, 'Executed');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (6, TRUE, 'Expired');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (7, TRUE, 'Renewed');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (8, TRUE, 'Terminated');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (9, TRUE, 'Cancelled');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (10, TRUE, 'Rejected');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (11, TRUE, 'Deleted');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (12, TRUE, 'Inactive');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (13, TRUE, 'Active');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (14, TRUE, 'InProgress');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (15, TRUE, 'Completed');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (16, TRUE, 'Pending');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (17, TRUE, 'Closed');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (18, TRUE, 'Open');
INSERT INTO public."Statuses" ("Id", "IsActive", "Name")
VALUES (19, TRUE, 'Reopened');

INSERT INTO accounting."TransactionTypes" ("Id", "CreatedBy", "CreatedDate", "Description", "IsActive", "LastStatusId", "ModifiedBy", "ModifiedDate", "Multiplier", "Name", "StatusChangedBy", "StatusChangedDate", "StatusId", "UniqueIdentifier")
VALUES (1, NULL, TIMESTAMPTZ '2023-12-09T20:35:38.598924Z', 'Credit transaction', TRUE, NULL, NULL, NULL, 1, 'Credit', NULL, NULL, 13, NULL);
INSERT INTO accounting."TransactionTypes" ("Id", "CreatedBy", "CreatedDate", "Description", "IsActive", "LastStatusId", "ModifiedBy", "ModifiedDate", "Multiplier", "Name", "StatusChangedBy", "StatusChangedDate", "StatusId", "UniqueIdentifier")
VALUES (2, NULL, TIMESTAMPTZ '2023-12-09T20:35:38.598924Z', 'Debit transaction', TRUE, NULL, NULL, NULL, -1, 'Debit', NULL, NULL, 13, NULL);

CREATE INDEX "IX_Accounts_LastStatusId" ON accounting."Accounts" ("LastStatusId");

CREATE INDEX "IX_Accounts_StatusId" ON accounting."Accounts" ("StatusId");

CREATE INDEX "IX_AccountTransactions_AccountId" ON accounting."AccountTransactions" ("AccountId");

CREATE INDEX "IX_AccountTransactions_LastStatusId" ON accounting."AccountTransactions" ("LastStatusId");

CREATE INDEX "IX_AccountTransactions_StatusId" ON accounting."AccountTransactions" ("StatusId");

CREATE INDEX "IX_AccountTransactions_TransactionTypeId" ON accounting."AccountTransactions" ("TransactionTypeId");

CREATE INDEX "IX_TransactionTypes_LastStatusId" ON accounting."TransactionTypes" ("LastStatusId");

CREATE INDEX "IX_TransactionTypes_StatusId" ON accounting."TransactionTypes" ("StatusId");

SELECT setval(
    pg_get_serial_sequence('public."Statuses"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM public."Statuses") + 1,
        nextval(pg_get_serial_sequence('public."Statuses"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('accounting."TransactionTypes"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM accounting."TransactionTypes") + 1,
        nextval(pg_get_serial_sequence('accounting."TransactionTypes"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231209203540_Initial', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE accounting."Accounts" ADD "CurrencyId" text;

CREATE TABLE public."Countries" (
    "Id" text NOT NULL,
    "Code" text,
    "IsActive" boolean NOT NULL,
    "Name" text,
    "Description" text,
    "UniqueIdentifier" text,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedDate" timestamp with time zone,
    "CreatedBy" text,
    "ModifiedBy" text,
    "StatusId" integer NOT NULL,
    "LastStatusId" integer,
    "StatusChangedBy" text,
    "StatusChangedDate" timestamp with time zone,
    CONSTRAINT "PK_Countries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Countries_Statuses_LastStatusId" FOREIGN KEY ("LastStatusId") REFERENCES public."Statuses" ("Id"),
    CONSTRAINT "FK_Countries_Statuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES public."Statuses" ("Id") ON DELETE CASCADE
);

CREATE TABLE accounting."Requests" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Time" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Requests" PRIMARY KEY ("Id")
);

CREATE TABLE public."Currencies" (
    "Id" text NOT NULL,
    "Symbol" text,
    "NumericCode" integer,
    "AlphabeticCode" text,
    "CountryId" text,
    "IsActive" boolean NOT NULL,
    "Name" text,
    "Description" text,
    "UniqueIdentifier" text,
    "CreatedDate" timestamp with time zone NOT NULL,
    "ModifiedDate" timestamp with time zone,
    "CreatedBy" text,
    "ModifiedBy" text,
    "StatusId" integer NOT NULL,
    "LastStatusId" integer,
    "StatusChangedBy" text,
    "StatusChangedDate" timestamp with time zone,
    CONSTRAINT "PK_Currencies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Currencies_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES public."Countries" ("Id"),
    CONSTRAINT "FK_Currencies_Statuses_LastStatusId" FOREIGN KEY ("LastStatusId") REFERENCES public."Statuses" ("Id"),
    CONSTRAINT "FK_Currencies_Statuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES public."Statuses" ("Id") ON DELETE CASCADE
);

UPDATE accounting."TransactionTypes" SET "CreatedDate" = TIMESTAMPTZ '2023-12-13T11:46:02.608495Z'
WHERE "Id" = 1;

UPDATE accounting."TransactionTypes" SET "CreatedDate" = TIMESTAMPTZ '2023-12-13T11:46:02.608496Z'
WHERE "Id" = 2;

CREATE INDEX "IX_Accounts_CurrencyId" ON accounting."Accounts" ("CurrencyId");

CREATE INDEX "IX_Countries_LastStatusId" ON public."Countries" ("LastStatusId");

CREATE INDEX "IX_Countries_StatusId" ON public."Countries" ("StatusId");

CREATE INDEX "IX_Currencies_CountryId" ON public."Currencies" ("CountryId");

CREATE INDEX "IX_Currencies_LastStatusId" ON public."Currencies" ("LastStatusId");

CREATE INDEX "IX_Currencies_StatusId" ON public."Currencies" ("StatusId");

ALTER TABLE accounting."Accounts" ADD CONSTRAINT "FK_Accounts_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES public."Currencies" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231213114604_Schema.Country', '8.0.0');

COMMIT;

